### ISSUE TITLE
Owners bot appears to be using outdated data

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#1003]
I recently saw this set of parser errors at the bottom of the [owners tree](http://ampproject-owners-bot.appspot.com/tree):

![image](https://user-images.githubusercontent.com/26553114/96520915-1b496800-123e-11eb-8d47-3c94844de671.png)

At first, I thought the owners files in question needed to be updated after our recent WG refactor. But when I searched for them, they all seem to have been deleted. Perhaps owners bot is using outdated data? Or is there something else at play that I'm not seeing?

**Comment by rcebulko** [comment]
This is a product of the Owners Bot's caching mechanisms. It (intentionally) greedily accepts new OWNERS files while waiting a long time to drop deleted ones (or deleted directories). When I checked for this, it was no longer present
