### ISSUE TITLE
[owners] Add a mechanism to recognize specific bot accounts as legitimate reviewers

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#1283]
**Background:**

We're in the process of streamlining package update PRs by having them automatically approved and merged if all CI checks pass. See https://github.com/ampproject/amphtml/issues/33959. Owners bot is one such CI check that needs to go green when the correct bot automatically approves these PRs.

**Problem:**

Today, owners bot provides the `reviewerTeam` mechanism to allow only certain GH IDs to approve PRs and satisfy the owners check. GH teams require a two step process to add an ID: a) sending an invitation to join the team, and b) manually accepting the invitation. While this works for individuals, not all bot accounts can do b) unless there is an individual managing it. See https://github.com/ampproject/amphtml/pull/34148#issuecomment-831308299 for more details.

**Here's a potential proposal:**
- Add a new field to the owners file spec called `reviewerBots` that is similar to `reviewerTeam`
- Allow it to be added to the root OWNERS file (and only that file)
- If the setting is present, have the parser include those accounts in the list of valid approvers

With this, we will no longer have to automatically give bot accounts the other privileges that come with being a member of the `reviewerTeam`.

@rcebulko Do you see any downsides to this approach?

**Comment by rcebulko** [comment]
I think this approach is more complexity than necessary. Currently, the `reviewerTeam` property expects a string and is parsed into `new ReviewerSetRule(ownersPath, [new TeamOwner(reviewerTeam)])`. This property should just be replaced with `reviewerPool` or something similar, and the code in parser.js would become
```javascript
const parseReviewer = (rev) => this._parseOwnerDefinition(ownersPath, {owner: rev});
new ReviewerSetRule(ownersPath, reviewerPool.map(parseReviewer);
```

The existing logic around rule membership should apply automatically to the list of team/user owners. Updating the validation schema to reflect this change should be relatively straghtforward.

**Comment by rsimha** [comment]
I like the idea of switching `reviewerTeam` to the less restrictive `reviewerPool` which can contain both team names and individual accounts. Will draft a PR to implement this across the board and loop you in on the review.

**Comment by rcebulko** [comment]
I'll take care of it; gimme 5

**Comment by rcebulko** [comment]
See above
