### ISSUE TITLE
Owners Bot: Comments during Draft PRs leads to noise

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amp-github-apps#1316]
Eg, Owners Bot notified me to https://github.com/ampproject/amphtml/pull/34562, which is still a draft PR. Please have it ignore draft PRs until they become ready to review.

**Comment by rcebulko** [comment]
They are ignored already (as is any PR with "do not submit" in the title iirc). I created the PR normally by mistake, then switched it to draft afterwards
. Owners Bot is wiser than its creator.
