### ISSUE TITLE
Apply a failed status when tests fail

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#135]
Today, failing checks result in a neutral status. These should be red X marks. (Unless there's a reason why this can't be done yet?)

![image](https://user-images.githubusercontent.com/26553114/58359521-dc00c700-7e51-11e9-8196-07bb56210330.png)

**Comment by danielrozenberg** [comment]
Duplicate of #102 (context in PR #103)

**Comment by rsimha** [comment]
Gotcha. In that case, let's fix #102 soon.
