### ISSUE TITLE
Consider making `wg-runtime` the approver for bundle size increases

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#141]
Today, we assign runtime bundle size increases for review to a randomly selected individual from a [hard-coded set of reviewers](https://github.com/ampproject/amphtml-build-artifacts/blob/master/bundle-size/OWNERS).

I'm proposing that this be changed to the members of the [`wg-runtime`](https://github.com/orgs/ampproject/teams/wg-runtime) team, who are more familiar with whether a core runtime size increase can be avoided.

/cc @ampproject/wg-runtime

**Comment by kristoferbaxter** [comment]
@rsimha – Yes, agree. @ampproject/wg-performance members should be able to similarly to @ampproject/runtime.

**Comment by danielrozenberg** [comment]
This has now been deployed. Members of @ampproject/wg-runtime, @ampproject/wg-performance, and @ampproject/wg-infra are allowed to approve bundle-size increases, but only members of @ampproject/wg-runtime will be auto-assigned to review PRs
