### ISSUE TITLE
Dynamically get Travis VM IP addresses for authentication

### ISSUE THREAD

**Issue by estherkim** [ampproject/amp-github-apps#198]
Seen in the bundle size bot and test-status bot, Travis VM IP addresses are hardcoded to determine that an API request is coming from Travis, although in practice, IP addresses are subject to change and are out of our control.

I've seen some instances in Travis where the job fails because the IP address falls outside the accepted range. Example here - https://travis-ci.org/ampproject/amphtml/jobs/550468070

My suggestion is to use a service account or another authentication method that doesn't rely on IP addresses.

**Comment by danielrozenberg** [comment]
Unfortunately Travis doesn't provide any other way to validate that requests come from their jobs (unless we jump through hoops of going back and forth between APIs, but this seemed like an overkill to me). They recommend looking up their IP address as a way to validate

I updated both apps with the [latest list](https://docs.travis-ci.com/user/ip-addresses/) from Travis and signed up to the mailing list to get updates when they change those. If you have any other ideas how to fix this, let me know :/

**Comment by estherkim** [comment]
Thanks Daniel! Subscribing to IP address changes seems fine to me. I might have to do something similar for the pr-deploy bot so I'll let you know if I find an alternate solution.

**Comment by rsimha** [comment]
Haven't seen this in a while.

**Comment by danielrozenberg** [comment]
After discussing this offline - Travis suggests using an API endpoint to get the latest list of IP addresses. See https://docs.travis-ci.com/user/ip-addresses/

This should be fixed on both the bundle-size and test-status apps

**Comment by estherkim** [comment]
The pr-deploy bot could use it too - can this be a shared service?

**Comment by danielrozenberg** [comment]
Probably ^__^

**Comment by rcebulko** [comment]
So, we need to nail down if we want A) a shared service or B) an API call on-demand.

Arguments in favor of a shared service:
- Single source of truth
- No risk of hitting some form of rate-limit
- Reduced dependency on a 3rd-party service being up
- No API request for every request by Travis

Arguments in favor of on-demand:
- Keep IP checking code very simple
- No dependency on a separate GAE app
- No Cloud Storage request for every request by Travis
- IP source always up-to-date

**Comment by rcebulko** [comment]
@danielrozenberg @rsimha @estherkim If y'all also have strong opinions here, might make sense to leave the gist as a comment so we can add/read asynchronously and we'll be able to skip a lot of back-and-forth whenever we do actually meet

**Comment by estherkim** [comment]
Thanks for the summary @rcebulko!

I like option B) for these reasons:
1. Less complex and reduced dependencies - it doesn't rely on GAE/GCS/the app itself.
2. Uses the authoritative source (nat.travisci.net) in real time.
3. All logic lives in this repo / nodejs land - MUCH easier for anyone to maintain or debug.

With either option, we can reduce XHRs sent to nat.travsci.net or GCS by keeping an ip address cache in memory, or setting env vars.

**Comment by danielrozenberg** [comment]
We should definitely at least use some caching strategy here. Calling a 3rd
party on _every request_ is not a good idea and might even be against their
terms of service :/

**Comment by rcebulko** [comment]
Do we have an idea of roughly how many requests we get a day?

**Comment by rcebulko** [comment]
It seems really unlikely that we'll have any trouble with rate limits on DNS requests if we are doing one DNS lookup on Travis for each request Travis sends to us

**Comment by rcebulko** [comment]
Also +1 to an N-hour local cache in the apps that support it. I'm not sure which ones have persistent state and which are only spun up in response to webhooks (not familiar with Probot)

**Comment by estherkim** [comment]
> Also +1 to an N-hour local cache in the apps that support it. I'm not sure which ones have persistent state and which are only spun up in response to webhooks (not familiar with Probot)

Once a Probot app is deployed, it's up and running via GAE unless you take it down. Currently IP address ranges stored in node env variables and works well (until Travis changes them, hence this issue).

> We should definitely at least use some caching strategy here. Calling a 3rd party on _every request_ is not a good idea and might even be against their terms of service :/

Agreed. We could keep the ranges hard coded, and send an XHR only when an incoming IP address is unrecognized. In that single XHR we can authenticate the address and update the ranges. Given that this service will be updating accepted ranges, I'm unsure if node env is the best way to keep them.

**Comment by rcebulko** [comment]
+1 to update-on-invalid

**Comment by rcebulko** [comment]
@danielrozenberg Does this sound reasonable?

**Comment by danielrozenberg** [comment]
Update on invalid might be more complex than just having it run as a `setInterval` job that updates an in-memory cache every ~1 hour :)

**Comment by estherkim** [comment]
Sure :) @rcebulko how does this sound? I know you pretty much created A) already but hopefully we can reuse it for something else in the future.

**Comment by rcebulko** [comment]
Yep SGTM. There's minimal benefit to keeping the rest of A) around, so I'll pull that out. If we ever want it for some reason, that's what Git is for :)

**Comment by rcebulko** [comment]
@estherkim Reviewing my open issues/trying to determine if this should be shelved; in your experience, roughly how often do Travis VM IPs change?

**Comment by danielrozenberg** [comment]
Pretty often unfortunately :/

**Comment by rcebulko** [comment]
@danielrozenberg Since we don't actually do this check anymore, is it reasonable to close this issue as obsolete?

**Comment by danielrozenberg** [comment]
We're not doing the check *because* this issue is still open... this should still be fixed so we can reactivate the check

**Comment by danielrozenberg** [comment]
We no longer use Travis so this isn't relevant
