### ISSUE TITLE
Several security vulnerabilities seen in `amp-github-apps` repo

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#270]
We should ~enable renovate for~ upgrade the packages in this repo to fix these and future security vulnerabilities.

![image](https://user-images.githubusercontent.com/26553114/61657744-acbfd800-ac91-11e9-9752-78d77bcae9fd.png)

![image](https://user-images.githubusercontent.com/26553114/61657725-a0d41600-ac91-11e9-99fc-68d4ab35d979.png)

**Comment by danielrozenberg** [comment]
renovate-bot is [already on for this repo](https://github.com/ampproject/amp-github-apps/pulls/renovate-bot), and all renovate-bot PRs that I haven't approved are assigned to @estherkim, @erwinmombay, and @rcebulko

**Comment by rsimha** [comment]
The purpose of this issue is to track the fixing of security vulnerabilities. I've edited the description. Reopening until the alerts are gone.

**Comment by rcebulko** [comment]
Is there a way for us to see open vulnerabilities, or only repo admins/owners?

**Comment by rsimha** [comment]
@rcebulko You should have access once you become a part of @ampproject/wg-infra. Let's chat offline about how we can make that happen.

**Comment by rsimha** [comment]
Curious: For all the packages that you manually upgraded, were there renovate PRs that we couldn't merge for some reason or the other?

**Comment by rcebulko** [comment]
There had been a renovate PR for a while for Probot, but it broke owners, so I finally got to the bottom of that and fixed it. Jest, I don't recall seeing a renovate PR, and there was nothing pending. According to `npm outdated`, `test-status` was fine; it was just that `set-value` was a transitive dependency of a few direct dependencies that hadn't yet upgraded themselves.
