### ISSUE TITLE
[owners] allow for special "*" rule on owners.yaml that makes files not need approvals

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amp-github-apps#279]
this is because top level files will be constanty requested reviews from root level OWNERS. we need a way to make the top level files easier to be edited and approved.

**Comment by rcebulko** [comment]
Related to/possibly dependent on #278

**Comment by rcebulko** [comment]
This may be rendered unnecessary once we support teams; at most, it will be syntactic sugar for the "everyone" team

**Comment by rcebulko** [comment]
Re-opening for the syntactic sugar/easier to use than teams.
