### ISSUE TITLE
[owners] Better link to status message

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amp-github-apps#280]
For AMP this might be an OK link
https://github.com/ampproject/amphtml/blob/master/GOVERNANCE.md#owners

But we should probably have a dedicated doc in https://github.com/ampproject/amphtml/tree/master/contributing

**Comment by rcebulko** [comment]
I'm not clear on what the "status message" is referring to

**Comment by rcebulko** [comment]
@erwinmombay Can you add some context on this? I'm not clear on what needs to be updated

**Comment by rcebulko** [comment]
Closing as obsolete/duplicate of #282
