### ISSUE TITLE
[owners] Provide a comment with instructions at the top of every `OWNERS.yaml` file 

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amp-github-apps#282]
When someone new to the codebase wants to edit an OWNERS.yaml file, it's hard to find the format for declaring owners for individual files / directories, and for declaring a working group as an owner.

A single line comment that points to the OWNERS.yaml spec would be useful.

I'm happy to write up a PR if a link exists.

**Comment by rcebulko** [comment]
@rsimha @erwinmombay Can y'all confirm no such spec exists? If not, I'll write one up in the near future as a way to familiarize myself a bit with what features exists or are intended.

**Comment by rsimha** [comment]
We have go/amp-codeowners (internal), but it doesn't contain details of the `OWNERS.yaml` format. Might be worth adding it to the doc while fixing this issue.

**Comment by rcebulko** [comment]
SGTM

**Comment by rcebulko** [comment]
Should be addressed with validation/OWNERS syntax checks in #281

**Comment by rcebulko** [comment]
Related: Pull #438

**Comment by rsimha** [comment]
@rcebulko I was trying to make some edits to an `OWNERS.yaml` file, and had to look around for a while before I could find the recommended format. Would it be possible to post a comment at the top of every `OWNERS.yaml` file with a link to this file?

**Comment by rcebulko** [comment]
Currently it's linked in the bot output, but obviously that's not useful until after you've already make the changes to the owners file. I'll put together a PR adding a comment with a link to all the files.

**Comment by rcebulko** [comment]
Closed with above PR
