### ISSUE TITLE
[owners] Provide a mechanism to allow certain files to be exempt from owners checks

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amp-github-apps#286]
For example, package.json gets updated very frequently by the renovate bot. A build cop should be able to approve and merge those PRs without needing a review from the individual owners of the root directory (or that file).

**Comment by rcebulko** [comment]
Possible duplicate, or at least relation to, #283

**Comment by rcebulko** [comment]
Closing as a duplicate of #279
