### ISSUE TITLE
Enable prettier for the `amp-github-apps` repo

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#316]
For consistency, let's use the same `.prettierrc` as `amphtml`.

**Comment by rsimha** [comment]
@rcebulko Reopening this since the code doesn't actually follow the format recommended by prettier. (You'd need to run `eslint` with `--fix` and change the `prettier` entry in `.eslintrc` from a warning to an error.)

**Comment by rcebulko** [comment]
@rsimha On the Prettier PR @erwinmombay suggested making it a warning rather than an error. I'll spin up a linted PR with the changes and loop you both in as reviewers.
