### ISSUE TITLE
Create release tagging bot

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp-github-apps#348]
Something like this already coded in  https://github.com/ampproject/amphtml/blob/master/build-system/tasks/release-tagging.js, but it's not running consistently to my knowledge.

Here's how it'd work:

1. As soon as a release is created/change, a pull request appearing in the release's changelog gets tagged with the release number: via custom labels and/or comments. Ideally subscribers would get a notification "this pull request went into a release 12345".
2. When a release goes into canary or prod the associated pull requests get a label "in canary" or "in prod". Possibly also comments are added as well for notification.
3. The same tags/comments are extended to issues closed by an associated pull request. This is important, since most of people actually track issues and not pull requests.

/cc @rsimha

**Comment by rsimha** [comment]
Thanks for the FR, @dvoytenko! We've talked about resurrecting the "in canary" / "in prod" labels in the past. It will definitely help solve problems like these:

- https://github.com/ampproject/amphtml/issues/17829
- https://github.com/ampproject/amphtml/issues/18551

**Comment by rsimha** [comment]
Thanks for taking this on, @estherkim!
