### ISSUE TITLE
[owners] Support no-notify and always-notify owners

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#395]
Some contributors, such as top-level owners, may not want to be automatically notified or added as a reviewer to PRs. In other cases, some contributors may have horizontal ownership over a wide range of directories, such as over *.protoascii files. For these cases, we should support special syntax. Suggestion:

- `?someuser`: The user `someuser` is an owner, but should not be auto-notified or added as a reviewer by the bot; they can be suggested by the bot, and added manually when the PR is ready for final approval
- `!someuser`: The user `someuser` is an owner, and even when their review is not required, they should always be notified/tagged/added as a reviewer so they can monitor changes
- `!!someuser`: The user `someuser` is a "super-owner" of the directory/file-pattern, and changes to the covered files may not be submitted without their approval

/cc @rsimha

**Comment by danielrozenberg** [comment]
I like the `?` syntax - this was a problem we had with the bundle-size bot where we wanted some people to be able to review PRs, but not have them auto-added as reviewers.

The `!` syntax is also useful, but I'm not sure whether the `!!` syntax is a little over-engineery. I can't imagine a reasonable scenario where a `!` user is notified, says nothing, and then regrets it after the PR has been merged by other OWNERS

**Comment by rcebulko** [comment]
@danielrozenberg Suppose `languageperson` should have veto power over any `*.protoascii` file changes, and I'm an owner of `extensions/amp-foo`. I could create `extensions/amp-foo/stuff.protoascii`, get a review from anyone, and submit (since I own it, I can approve it). In that case, it could be submitted before `languageperson` ever gets the chance to see it or approve/reject.

I agree it's a corner-case, and probably worth holding off on implementing `!!` until we see a need arise.

**Comment by honeybadgerdontcare** [comment]
For `*.protoascii` files I believe `!someuser` would be sufficient. Being aware of an incoming change to validation rules is helpful but we don't always need to be gatekeepers of it as some changes are fairly straight-forward.

**Comment by rcebulko** [comment]
@honeybadgerdontcare I'm a little unclear now; your comment on [this PR](https://github.com/ampproject/amphtml/pull/24518) suggests you *would not* need a "require-approval" gatekeeping syntax; whereas here you suggest you'd look forward to/need the ability to require approval. Would you mind clarifying how important each is to you/your subteam?

**Comment by honeybadgerdontcare** [comment]
Sorry for the confusion.

At this point in time I do not believe we need to be gatekeepers of `extensions/validator-*.protoascii` but only be informed of them. If in time we find it necessary to be gatekeepers of `extensions/validator-*.protoascii` then we would want to use `!!someuser` syntax.

Typically validator rules review take less time than the javascript review so we have ample time to review it. Further these rules don't compile into the production javascript until they've been imported internally and compiled to validator.js. That allows us to have a second opportunity to review them then.

Any changes to `validator/...` we would be gatekeepers of because that could involve changes to the validator engine.

**Comment by rcebulko** [comment]
Excellent, thanks!

**Comment by rcebulko** [comment]
Initially, I'll be implementing no-notify `?` and always-notify `!` modifiers. After this, I plan to also add an only-notify `*` modifier, which will notify the owner(s) but will not give them ownership. This would be useful for monitoring things, like if the UI team wanted to monitor any CSS file changes or if I wanted to be notified of all changes to OWNERS.yaml files, but I shouldn't necessarily be able to approve all changes.

**Comment by rcebulko** [comment]
Since there is a need for an "always-require" modifier, meaning a file requires approval from a particular owner even when they have approval from another owner, the planned syntax will be updated as follows: 
`!` - require review
`#` - always notify/tag
`?` - never auto-add reviewer

**Comment by rcebulko** [comment]
Support for `#` and `?` has been added.

**Comment by rsimha** [comment]
@rcebulko Thanks for working on this!
