### ISSUE TITLE
[pr-deploy] Provide website app landing page instead of cloud console

### ISSUE THREAD

**Issue by wassgha** [ampproject/amp-github-apps#397]
Came up because some features aren't available on iOS Safari without a "secure context". In particular, it's not possible to demo PRs that have `devicemotion` listeners

**Comment by wassgha** [comment]
White we're at it, is it possible for the pr-deploy bot to show the link to the website instead of the Cloud Console?

**Comment by estherkim** [comment]
No I think you're doing it right. It definitely is a little clunkier than using the app interface when doing local debugging at `localhost:8000`. I'll consider it as something to implement, especially if that drives more people to use this feature!
