### ISSUE TITLE
[owners] Do not @mention an owner if they are already assigned as a reviewer.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amp-github-apps#473]
Do not @mention an owner if they are already assigned as a reviewer.

Context: https://github.com/ampproject/amphtml/pull/24709#issuecomment-534619745

**Comment by newmuis** [comment]
Maybe should also apply to the author?

**Comment by gmajoulet** [comment]
+1, but I think Ryan already submitted this one: https://github.com/ampproject/amp-github-apps/pull/468

**Comment by rcebulko** [comment]
Correct, the author is already excluded (update just isn't rolled out yet)
