### ISSUE TITLE
Are project metrics accurate?

### ISSUE THREAD

**Issue by estherkim** [ampproject/amp-github-apps#474]
**Potential bug 1**: the contributors badge count is different than the repo's contributor count
![image](https://user-images.githubusercontent.com/44627152/65537306-fbc4fc00-ded2-11e9-8049-9772297a61fa.png)
and
![image](https://user-images.githubusercontent.com/44627152/65537320-041d3700-ded3-11e9-91b1-04d8d74c320a.png)

**Potential bug 2**: the cherry pick PR count seems too high. Also shouldn't we be counting issues, not PRs?
![image](https://user-images.githubusercontent.com/44627152/65537440-362e9900-ded3-11e9-9a8a-399606c5cf5f.png)
and
[19 cherry pick issues since 6/27/2019](https://github.com/ampproject/amphtml/issues?utf8=%E2%9C%93&q=is%3Aissue+Cherry-pick+request+created%3A%3E2019-06-27)

cc/ @ampproject/wg-infra

**Comment by rcebulko** [comment]
1) Contributors is not part of project metrics; please file that as a separate issue
2) The cherry-pick count is based on commits that are in release branches but not in master/canary, not based on GitHub issues.

**Comment by gmajoulet** [comment]
Re: 2
Isn't the process to cherry-pick commits from master to release branches? How could a cherry-picked commit be in a release branch but not in master?
Also, if we create multiple release branches (eg: two consecutive cherry-picks + release), wouldn't this process count the first cherry-pick twice?

**Comment by rcebulko** [comment]
Re: first part, since they're cherry-picked the commits are different, as in they have a different hash. So any commit SHAs in a release that are not present in master are commits that were cherry-picked onto the point at which the release was branched off of master.
Re: second part, could you clarify what you mean?

**Comment by gmajoulet** [comment]
I have no context on this project so feel free to correct me if I'm missing something. What you just said about the different hash invalidates my previous idea, but would the following scenario explain for the gap Esther found?

If a cherry-pick goes into canary + prod, the on duty engineer cherry-picks the commit into two different releases. Whether this should count as one or two cherry-picks is more of a product question, but could potentially introduce a gap between the number of cherrypick issues, and the number on the badge. Have you been discussing this already?

Also, if the onduty engineer re-creates a new release from `canary` and re cherry-picks all the commits instead of re-using the latest branch, you'd end up with a higher count on your badge.

**Comment by rcebulko** [comment]
I'm not certain how canary releases fit in. Is there a separate GitHub release for canaries vs master? My understanding was no?

**Comment by gmajoulet** [comment]
When a commit is cherry-picked into canary + prod, aren't two branches created (one for each), incrementing the badge count by 2?

**Comment by rcebulko** [comment]
Two branches are created, but I don't believe two distinct releases are. The cherry-pick counter works like:
- get the [GitHub releases](https://github.com/ampproject/amphtml/releases) (ignores pre-release and draft)
- look at the branch tied to that release
- count commits on that branch past the merge-base on master

**Comment by estherkim** [comment]
Hey @rcebulko, yes, 2 branches are created to become 2 releases. 

Re: cherry-pick counter logic, I see several issues -
- a cherry pick can include multiple commits. 1 commit != 1 cherry pick.
- to @gmajoulet's point, if there are 2 consecutive cherry picks, it counts it as 3 (commit1 from branch1, plus commit1 and commit2 from branch2)
- it doesn't account for cherry picks that go into canary only (pre-releases on GitHub). Maybe that's by design.

Expanding on the last point, then it sounds like we are only counting prod cherry picks. If that's the case, 29 cherry picks in the badge does not seem right when there are only 19 cherry pick issues. What do you think?

**Comment by rcebulko** [comment]
The project design defined the metric as "This metric measures the total number of cherrypicks on releases that were deployed to production, for releases that were started over the past 90 days." The idea of including canary/RC cherry-picks was considered, but never added to the final design. 

The choice to use commits was made in part to parallel existing internal metrics, and in part because there was not a consistent enough source of truth re: cherry-pick issues. That there are more cherry-picks than cherry-pick issues indicates that either there were cherry-picks merged outside the cherry-pick issue process; some CP issues resulted in a commit being cherry-picked onto two separate releases; or some cherry-pick issues included multiple commits

**Comment by estherkim** [comment]
> there were cherry-picks merged outside the cherry-pick issue process; 

This does not and should not happen.

> some CP issues resulted in a commit being cherry-picked onto two separate releases; or some cherry-pick issues included multiple commits

If we are set on counting commits and not cherry picks, let's change the badge name to be less misleading.

**Comment by estherkim** [comment]
re: bug 1, new issue filed here https://github.com/ampproject/amp-github-apps/issues/475

**Comment by rcebulko** [comment]
The badge says explicitly `X PRs/90days`

**Comment by rcebulko** [comment]
Do we have another way to reliably get cherry-picks?

**Comment by estherkim** [comment]
Yes, the # of cherry pick issues is a reliable source of information. Implementation is up to you but there should be a GitHub API for issues. It might be difficult to decipher from the issue body whether it's a prod or canary cherry pick. In this case, I'm okay with including all cherry picks in the badge if you are.

Also a small note, unless the logic is averaging the # of commits over time, the badge should say `X PRs in the last 90 days`.

**Comment by rcebulko** [comment]
At the time it was implemented, the issues were inconsistent/there was no reliable, consistent pattern that could be used to identify cherry-picks, and there were cherry-picks without associated issues. Has the process improved that it can now be considered a source of truth?

**Comment by rcebulko** [comment]
Re: the badge text, the metric value text is intentionally much shorter, but the hover text is "Number of cherry-picks in releases over the last 90 days", which I think is a sufficient explanation

**Comment by gmajoulet** [comment]
Quick followup on this:

![image](https://user-images.githubusercontent.com/1492044/69167144-7456cc00-0ac2-11ea-8b7b-bde461a85c99.png)

This screenshot shows 37 cherry-picks even though I only count [13 to 15](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+Cherry-pick+request+is%3Aclosed) in the GitHub issues.

**Comment by rcebulko** [comment]
It counts all commits in a cherry-pick, which is sometimes multiple commits, so I think that's adding to it. If you'd like to dig in, here's the releases in the last 3 months and how many cherry-pick commits the DB has for them:

```
+---------------+----------------------------+----------+
| name          | MAX(releases.published_at) | COUNT(1) |
+---------------+----------------------------+----------+
| 1908162035200 | 2019-08-19 17:02:42        |        3 |
| 1908162134430 | 2019-08-19 15:51:51        |        5 |
| 1908222134250 | 2019-08-23 16:20:11        |        1 |
| 1908231648370 | 2019-08-29 18:30:06        |        2 |
| 1909051756330 | 2019-09-05 19:12:48        |        2 |
| 1909131932180 | 2019-09-13 20:21:41        |        3 |
| 1909141409590 | 2019-09-14 15:04:26        |        4 |
| 1909141411050 | 2019-09-14 15:04:38        |        1 |
| 1910071803120 | 2019-10-07 22:07:55        |        4 |
| 1910071804120 | 2019-10-07 22:33:53        |        4 |
| 1910251950120 | 2019-10-25 23:59:15        |        1 |
| 1910302211460 | 2019-10-31 21:00:52        |        1 |
| 1911042323000 | 2019-11-05 04:00:54        |        4 |
| 1911052130250 | 2019-11-06 15:52:42        |        1 |
| 1911062056110 | 2019-11-07 03:20:46        |        1 |
+---------------+----------------------------+----------+
```
If and when the cherry-pick scraper in the app is updated to use cherry-pick GitHub issues, it can be rerun to update historic values.

**Comment by rcebulko** [comment]
I'll add that, looking through cherry-pick issues, not all are properly updated to indicate whether or not they were approved and merged; not all have a `Type: Release` label; and some are multiple-PR cherry-picks. These were among the reasons we opted to count # commits cherry-picked versus trying to guess at the # of PRs

**Comment by rsimha** [comment]
> I'll add that, looking through cherry-pick issues, not all are properly updated to indicate whether or not they were approved and merged; not all have a `Type: Release` label; and some are multiple-PR cherry-picks. These were among the reasons we opted to count # commits cherry-picked versus trying to guess at the # of PRs

Yeah, I don't think there's an easy way to tell if a cherry pick went into production or not for all issues. Until such time, switching to a cherry pick count SGTM. Thanks for the discussion, everyone.

**Comment by rcebulko** [comment]
As long as the `Type: Release` label is applied to all actually cherry-picks, and only those cherry-picks, the metric will remain accurate
