### ISSUE TITLE
[owners] Only request reviews from members of `ampproject/reviewers-amphtml`

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#499]
Since some working groups contain owners without the ability to give approving reviews, it's possible people could be assigned as reviewers who can't actually provide the review/another reviewer would be needed. When suggesting reviewers, we should only suggest those in the `ampproject/reviewers-amphtml` group.

One concern to mind when implementing this is that this is a relatively `amphtml`-centric need, but the solution should be relatively repository-agnostic so that other repos utilizing the owners bot aren't adversely affected.

This shouldn't have any effect on ownership coverage; it should only filter out which users can be considered during the reviewer selection algorithm. Proposed approach:

- [ ]  Provide a `isAllowedReviewer(username) --> boolean` test function to the reviewer selection algorithm and filter when selecting reviewers
- [ ] Let `isAllowedReviewer` default to `username => true`
- [ ] Add a `ALLOWED_REVIEWERS_TEAM` env variable where a team can be supplied
- [ ] When `process.env.ALLOWED_REVIEWERS_TEAM` is present in the team list, provide `username => team.allUsernames.includes(username)` as the `isAllowedReviewer` test function (or some set-based variant)

@rsimha thoughts?

**Comment by rsimha** [comment]
> When suggesting reviewers, we should only suggest those in the `ampproject/reviewers-amphtml` group.

Agree, this should absolutely be the behavior.

The proposed approach sounds good in general. Re: `ALLOWED_REVIEWERS_TEAM`, are env variables the only means of passing data to a bot instance? Or is there an alternative way to configure an instance via, say, GCE settings?

**Comment by rcebulko** [comment]
Well...about that...

Currently the bot works by pushing to a cloud repository which is separate from this repo, which I wrote a script to do by copy-pasting from a local `amp-github-apps` repo to a local `amp-owners-bot` repo, then pushing. When you run `gcloud instances reset` (or something like that), it restarts the instance and runs a `startup-script` which is part of the GCE instance metadata and contains a combination of startup script things (logging, checking out code, installing stuff, starting node under `supervisord`) along will a bunch of both sensitive and standard env variables. So, GCE settings and env vars are kinda one big blob at the moment. In theory there is a metadata key-value store in GCE settings, but I'm uncertain how easy it is to access these values within the app. The first step will be to move public-safe (ie. not Oauth/API tokens and keys) to a `.env` file where possible, and strip the massive `startup-script` into smaller pieces that can be checked into the repo. As that happens, we'll have a better idea of what options are available to us re: configuration.

**Comment by rcebulko** [comment]
Update: Created tracking issue for the configuration/deployment issues #500

**Comment by rcebulko** [comment]
This is implemented; closing

**Comment by rsimha** [comment]
Reopening this issue based on a discussion on our team chat. Today, the following statement from the original discussion does not hold true:

> When suggesting reviewers, we should only suggest those in the ampproject/reviewers-amphtml group.

Any chance we can make it true so that suggested reviewers are selected from the intersection of the set of owners and the set of members of `ampproject/reviewers-amphtml`?
