### ISSUE TITLE
[owners] Deploy from `amp-github-apps` repo and check in startup script + env

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#500]
Currently the bot works by pushing to a cloud repository which is separate from this repo (since the project was started in its own repo), which I wrote a script to do by copy-pasting from a local `amp-github-apps` repo to a local `amp-owners-bot` repo, then pushing. When you run `gcloud instances reset` (or something like that), it restarts the instance and runs a `startup-script` which is part of the GCE instance metadata and contains a combination of startup script things (logging, checking out code, installing stuff, starting node under `supervisord`) along will a bunch of both sensitive and standard env variables. So, GCE settings and env vars are kinda one big blob at the moment. In theory there is a metadata key-value store in GCE settings, but I'm uncertain how easy it is to access these values within the app. The first step will be to move public-safe (ie. not Oauth/API tokens and keys) to a `.env` file where possible, and strip the massive `startup-script` into smaller pieces that can be checked into the repo. As that happens, we'll have a better idea of what options are available to us re: configuration.

This fragile deployment and configuration introduces a significant risk of bringing down the owners bot when trying to deploy updates or change configuration. It also present a significant obstacle to any other consumers of the owners bot app, since the core deployment and environment are not visible in the public repo.

/cc @rsimha @erwinmombay

**Comment by rcebulko** [comment]
(Incomplete list of) steps to clean up startup script:
- [ ] Check in current startup script
- [ ] Identify which steps of the startup script are required for initialization vs. re-deploying a new version
- [ ] Update the script to clone/pull from this repository instead of the old one living in GCP
- [ ] Identify which environment variables are used and by what (setup, Probot, and/or the app)
- [ ] Split into initialization and deployment scripts
- [ ] Instead of writing PEM key to a local file and setting `PRIVATE_KEY_PATH` env var, `echo` key through `base64` and set as `PRIVATE_KEY` env var
- [ ] Migrate to `dotenv` environment configuration (if possible?)

**Comment by danielrozenberg** [comment]
Is there a specific reason why you need this to be a GCP instead of GAE instance? (which takes away 99% of the problems you're having)

**Comment by rcebulko** [comment]
The app uses a locally checked out copy of the repo to read the OWNERS files from. It's conceivably possible to fetch a listing of all files in the repo from the GitHub API, identify OWNERS files, fetch the contents of each individually, and parse from there (while monitoring each for changes to update on), but that's not something that's currently planned.

**Comment by rcebulko** [comment]
Closing since #540 addresses some of this and makes the rest obsolete.
