### ISSUE TITLE
[owners] Migrate from GCE to GAE

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#540]
The original implementation of the Owners bot was based around a Google Compute Engine (GCE) deployment. This decision was made because GCE provides local filesystem I/O, which is useful for maintaining a copy of the repository, using command-line-fu to identify owners files, and reading the contents of those owners files. No other files are read, and none are written.

Using GCE introduces a handful of issues, most notably:
- deployment is fragile, takes down the app, and relies on a startup script that is not checked in
- there is no reliable way to manage environment variables (especially sensitive keys/tokens); they are just embedded in the startup script, and can't be checked into the repository used to deploy
- the team is less familiar with GCE than GAE, making maintenance and debugging harder
- firewall restrictions around GCE make SSH and debugging difficult
- the amount of bootstrapping and configuration embedded only in GCE instance metadata makes it hard/impossible for other projects to make use of the owners bot

As a resolution to these issues, the plan is to migrate to Google App Engine (GAE). This will be a lot of work up-front, but should make automated and continuous deployment and development of the app much easier and less error-prone going forward.

Steps needed to migrate to a GAE deployment process:
- [x] configure app to read from `.env` file; write the `.env` file within the startup script during migration
- [x] hoist a base `Repository` class out of the `LocalRepository` class, and implement a `RemoteRepository` subclass
  - [x] using the [GitHub code search API](https://developer.github.com/v3/search/#search-code), provide the `listOwnersFiles` method
  - [x] using the [GitHub file contents API](https://developer.github.com/v3/repos/contents/#get-contents), provide the `readFile` method
- [x] maintain a map from owners file paths to the SHA of their latest commit
- [x] implement a caching layer to prevent overloading GitHub API on file reads
- [x] lift the collection and parsing of owners files/the ownership tree out of the owners check and into a single server-shared tree
- [x] isolate bootstrapping code (ie. initializing teams and ownership trees)
- [x] add webhooks to catch updates to owners files and update the corresponding rules in the cache
- [x] create `app.yaml` and deploy to GAE
- [x] migrate team and tree updating code to use Cron tasks
- [x] spin down GCE version of app

/cc @rsimha @erwinmombay @danielrozenberg

**Comment by rcebulko** [comment]
One concern/point to be aware of:

Once the tree is initialized, it will only need to fetch file contents when the owners files change, which should be relatively rare. Initialization, however, will be API-expensive; there are roughly 150 Owners files in `ampproject/amphtml` at this time, and each must be fetched separately. There are two ways we should address this.

The first is by rate-limiting the initialization code. By separating calls to the file contents and team member APIs by a second or two, we can avoid hitting some rate limits.

We can also store the contents of each owners file as a blob in a Cloud Storage bucket. The `readFile` API can try to first read from the bucket, then re-fetch from the API the blob is not present in Cloud Storage. Cleanup strategy for old versions of owners files needs to be determined. The advantage of this persistence strategy is that startup and initialization will be much quicker, and wil avoid any risk of blasting the GitHub API to quickly.

Alternately, we could maintain a database within the GAE instance tracking the owners/files/rules keyed by owners file path-SHA pairs, updating the database whenever owners files change, and reading from the database to construct the tree.

The additional overhead of maintaining, updating, and interfacing with this database would introduce more maintenance costs than it's probably worth, so I lean toward the blob storage solution.

**Comment by rsimha** [comment]
Tagging @ampproject/wg-infra so everyone can chime in.

**Comment by rcebulko** [comment]
Also relevant: #575 #574 #573 #572 #576

**Comment by rcebulko** [comment]
My understanding was that smee was used for monitoring and debugging and re-sending webhook event payloads, not that it was a development-only thing. But I can revert it

**Comment by rcebulko** [comment]
Done in #586
