### ISSUE TITLE
GitHub Apps need homepage links set in project

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp-github-apps#554]
When amp-owners-bot check is viewed more details about, there's the following link:

![image](https://user-images.githubusercontent.com/250887/67220424-b2a88f00-f421-11e9-8e85-747ae50e4295.png)

This currently leads to https://www.ampproject.org which is probably a placeholder. We should probably have it lead to a doc explaining OWNERS.

**Comment by rcebulko** [comment]
On the roadmap for after #540

**Comment by rsimha** [comment]
Let’s do this for all our apps.

/cc @ampproject/wg-infra

**Comment by rcebulko** [comment]
This is done for Owners. It's a setting within the app configuration, so you'll have to sign into `ampprojectbot`, go to Settings > Developer Settings > _Your App_ and set the **Project Hompage** field

**Comment by rcebulko** [comment]
@danielrozenberg @estherkim @rsimha If y'all can post here what "homepage" you'd like the app to point to, I'll go update them all at once

**Comment by rsimha** [comment]
I think these links should point to the main README.md file for each app.

**Comment by rcebulko** [comment]
@rsimha I don't know if that's always the case. Speaking from the Owners Bot as an example, the homepage link would be reached by contributors clicking on the link from the Owners Check output page. To them, the README (which is mostly deployment and development instructions) would be less useful than the app server, with the example OWNERS syntax specs, the ownership tree, etc. I'm not sure if any of the other apps have a similar set of pages though.

**Comment by rsimha** [comment]
What if we standardized the links to point to the respective README files, and have them point to the syntax specs / ownership tree? That way, the README contents can be changed at any point without having to reconfigure individual apps.

**Comment by rcebulko** [comment]
That would tie the app code/repo directly to a specific deployment/URL, as opposed to an app installation (within GitHub) pointing to the instance that is receiving that installation's webhooks

**Comment by rcebulko** [comment]
(Though for apps that don't have any context pages, pointing to the readme is fine)

**Comment by rsimha** [comment]
> That would tie the app code/repo directly to a specific deployment/URL, as opposed to an app installation (within GitHub) pointing to the instance that is receiving that installation's webhooks

Fair point. I retract my suggestion.

**Comment by rcebulko** [comment]
I think it would be fine t opoint some of the app installations to the readme, but at least for Owners Bot I think it's more useful to point at the bot server

**Comment by rcebulko** [comment]
Updated the 3 GitHub apps to point at the README (Owners Bot still points to [the app status page](http://ampproject-owners-bot.appspot.com/)); resolving
