### ISSUE TITLE
[owners] bot not assigning reviewers to renovate PRs

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#556]
As can be seen in PRs listed below, the owners bot is not requesting reviews for `package.json` and `yarn.lock` dependency changes. It does appear to recognize approving reviews, and the owners check itself seems to be functioning normally.

I created https://github.com/ampproject/amphtml/pull/25193 to test assignment of root level files, and it requested a review from `mrjoro` as expected. This suggests the issue is likely not with the owners bot logic or review requesting, but instead is likely to be a quirk of how the GitHub API handles bot PRs and what the event payloads look like for the corresponding webhooks.

https://github.com/ampproject/amphtml/pull/25193
https://github.com/ampproject/amphtml/pull/23726
https://github.com/ampproject/amphtml/pull/25036

/cc @rsimha

**Comment by rsimha** [comment]
[Here](https://github.com/ampproject/amphtml/pulls?q=is%3Apr+author%3Arenovate-bot+is%3Aclosed) is the entire list of renovate PRs. Most of them were immediately assigned a reviewer, so it's unlikely that something fundamental is broken.

Some theories that you can eliminate:

- The PRs were created when auto-assigning of reviewers hadn't been turned on
- The PRs were created when you happened to be re-deploying owners bot
- Owners bot should listen to more PR events (rebasing a branch, force-pushing the same commits, editing the title, editing the description, etc.)

**Comment by rcebulko** [comment]
PRs that were created before auto-assigning would not get assigned; this is WAI. Same thing for edits, rebases, force pushes, etc. It only assigns on PR creation

**Comment by rsimha** [comment]
> PRs that were created before auto-assigning would not get assigned; this is WAI

My question was more about whether this is indeed what happened in the case of those PRs, not whether this is desired behavior (which it is).

**Comment by rcebulko** [comment]
Based on looking through the flagged PRs, it looks like they were created before reviewer assignment was enabled (or, in some cases, even implemented). Since the last 10 renovate PRs had reviewers assigned by the bot as expected, I'm closing this as Obsolete/WAI. If you notice it popping up oddly at some point in the future, feel free to re-open.
