### ISSUE TITLE
[owners] make the check have an "in progress" status (yellow dot) when PR has full coverage, but no approvals yet

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amp-github-apps#596]
So:
* Green (`success`): all approvals given
* Yellow (`in_progress`): current reviewers can give approval, but no approvals were given yet
* Red (`action_required`): current reviewers cannot give approval

That way most PRs will be yellow, not red, because the bot usually auto-assigns enough reviews to cover

/cc @ampproject/wg-infra @jridgewell

**Comment by rsimha** [comment]
IIRC, there was a previous discussion on this that I’m hoping @rcebulko can link us to. 

I’ll add a new state to the list: 
- Red (`action_required`): check errored for some reason.
