### ISSUE TITLE
Set up build targets/conditional test running for this repo

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#605]
As the number of apps in this repo grows, Travis testing is taking longer and longer because every test for every app is run each time. Instead, we should have a system like `ampproject/amphtml`'s  build targets, to only run the test command for apps with files changed in the PR.

The plan is to pretty much replicate the existing `build-targets.js` and `checks.js`, albeit with much simpler rules for now--only looking at whether some file in the app directory is changed, without implemented the more detailed unit/integration path detection and other tests used in `amphtml`. Edits can be made as needed later on.

/cc @ampproject/wg-infra

**Comment by danielrozenberg** [comment]
I'd say that if any file in the base directory was changed, run all the tests - otherwise, run only the tests for the project(s) whose subdirectories were changed. Should be Good Enough™ for now :)

**Comment by rcebulko** [comment]
That was my initial thought, but really most files in the base directory aren't relevant (readmes, dotfiles, etc). `eslint` is running regardless of targets, so even dotfile changes wouldn't impact tests for any apps. I put a rule in build-targets to run all targets for any changes to `build-system` or `(package(-lock)?.json`

**Comment by rsimha** [comment]
> I'd say that if any file in the base directory was changed, run all the tests - otherwise, run only the tests for the project(s) whose subdirectories were changed

+1 to this. Running all tests for any change in the root dir (vs. picking specific files) will make the repo resilient when a new file that affects all tests is introduced.
