### ISSUE TITLE
Adopt `gulp` and set up tasks for testing, linting, etc.

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#608]
May be worth discussing if the migration is worth it versus using `npm` scripts, since more of the work is handled on a per-app basis currently.

Back-reference to #606

**Comment by danielrozenberg** [comment]
I think we can nix this. Our build system for these apps is pretty solid and doesn't necessarily have to mirror `amphtml` perfectly. wdyt?

**Comment by rcebulko** [comment]
Agreed. We already have unified NPM scripts (`npm test` in particular). If we need some more unified infrastructure down the line, we can look at this again. For now our infra is pretty stable. Closing
