### ISSUE TITLE
Improve OWNERS check for new ad networks

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amp-github-apps#613]
When an ad network would like to create a new a4a implementation e.g. https://github.com/ampproject/amphtml/pull/25130 it involves creating a new directory: `extensions/amp-ad-network-<NAME>-impl/`

This directory can then have its own OWNERS file, but for the initial PR the bot suggests getting approval from `ampproject/wg-ui-and-a11y` as they own `extensions/*`.

It seems a bit odd that UI would need to approve new ad networks. The two current options seem to be 
1. Get UI approval
2. Create an empty directory with an OWNERS file, and check that in first (still needs UI approval?) 

These PRs are usually going to be from external contributors so 2 seems to be introducing even more complexity into the submitter's first time contribution.

My suggestion is to find a way to allow @ampproject/wg-ads to approve these PRs without having to take an extra step or find someone on the UI team. My understanding is that directory globs were discussed and omitted, so I am not sure what the best option to accomplish this would be. Adding wg-ads as the owner for all extensions seems like overkill.

to/ @ampproject/wg-infra

**Comment by rsimha** [comment]
Perhaps you could try using a wildcard pattern for directories that match `extensions/amp-ad-network-` and set `wg-ads` as the owner of that pattern?

Something like this in `extensions/OWNERS`:
```
    {
      pattern: 'amp-ad-network-*/**',
      owners: [{name: 'ampproject/wg-ads'}],
    },
```

@rcebulko, will this work? Or is the wildcard pattern not supported today?

**Comment by calebcordry** [comment]
@rsimha That was my original idea, but based on a brief conversation with @rcebulko it sounds like it might not be supported. He is the expert, so I will let him chime in.

**Comment by rcebulko** [comment]
We had opted against supporting wildcard directory patterns due to the potential for more complicated/confusing rule structures (note that the [Gerrit OWNERS plugin](https://chromium.googlesource.com/chromium/src/+/master/docs/code_reviews.md#owners-file-details) used by Chromium made the same design choice. Wildcard patterns in directories is certainly possible, but I wonder if it may be something better solved by looking at the structure of the repo.

For instance, extensions are typically all added to the root `extensions` directory`. Might it make sense to have `extensions/amp-ad-network-impls/*` or something similar?

**Comment by rcebulko** [comment]
Directory structure changes aside, my current inclination is still toward reducing allowed complexity in rule configuration. Creating an empty directory with an OWNERS file seems to be a fairly trivial step, especially compared against the time each new extension spends in development and review.

**Comment by rcebulko** [comment]
(I should add that, from an implementation standpoint, complexity is very low. Directory globs are supported by the underlying glob parser; they are explicitly disallowed by the parser.)

**Comment by rsimha** [comment]
> 2\. Create an empty directory with an OWNERS file, and check that in first (still needs UI approval?)

Pretty sure this won't help, and you'll still need UI approval.

> Might it make sense to have `extensions/amp-ad-network-impls/*` or something similar?

We rely on a flat structure for the `extensions/` directory, so this will need significant refactoring of extension and build-system code. Not impossible though.

> Adding wg-ads as the owner for all extensions seems like overkill.

What's the primary disadvantage of this? I'd imagine you could make select folks from `wg-ads` owners of `extensions/` without auto-assigning them PRs to review. You'd still need to manually add them as reviewers, but they'd at least have the ability to approve ad-network PRs without waiting for someone from the UI group to intervene.

**Comment by calebcordry** [comment]
> What's the primary disadvantage of this? I'd imagine you could make select folks from wg-ads owners of extensions/ without auto-assigning them PRs to review. You'd still need to manually add them as reviewers, but they'd at least have the ability to approve ad-network PRs without waiting for someone from the UI group to intervene.

This SGTM, I just wasn't sure if there was a more elegant solution.

**Comment by rcebulko** [comment]
> > 2. Create an empty directory with an OWNERS file, and check that in first (still needs UI approval?)
> 
> Pretty sure this won't help, and you'll still need UI approval.

This would work fine; you'd just need approval from an `extensions` owner for the new directory/owners file, then you'd have ownership of the new directory.  

> 
> > Might it make sense to have `extensions/amp-ad-network-impls/*` or something similar?
> 
> We rely on a flat structure for the `extensions/` directory, so this will need significant refactoring of extension and build-system code. Not impossible though.
> 

Gotcha

> > Adding wg-ads as the owner for all extensions seems like overkill.
> 
> What's the primary disadvantage of this? I'd imagine you could make select folks from `wg-ads` owners of `extensions/` without auto-assigning them PRs to review. You'd still need to manually add them as reviewers, but they'd at least have the ability to approve ad-network PRs without waiting for someone from the UI group to intervene.

Disadvantage is that now owners of `wg-ads` also have ownership of every single extension, which  is not desirable either (it's up for debate if all members of  `wg-ui-and-a11y` should have total ownership of all extensions too)

**Comment by rsimha** [comment]
Paging @kristoferbaxter @lannka for comment :)

**Comment by rcebulko** [comment]
I will say, I think it's desirable that any new directory (ie. any new extension, ads-impl or not) should require explicit approval

**Comment by rcebulko** [comment]
On the topic of flat `extensions` directory, while that change would be out of scope for this issue, I think it might be a worthwhile discussion (though I'm not certain what format/working groups such a discussion should involve). There's a handful of extensions that offer clear grouping options. `amp-ad-network-<vendor>-impl`, `amp-<vendor>-player`, `amp-access-<vendor>`, `amp-facebook-<action>`, `amp-viewer-<component>`, `amp-subscriptions-<vendor (currently google)>`. I'd be surprised if more examples don't find their way into the repo over time. Some strategy for organizing extensions (there's 145 of them right now!) might be worth investigating

**Comment by rsimha** [comment]
> On the topic of flat `extensions` directory ...

Off the top of my head, this will need non-trivial changes to source code, compilation code, multiple CI checks, documentation, and release code.

Also, AMP extensions are served in a flat structure to make it easy for page authors to include an extension without having knowledge of a directory structure. A whole lot gets simplified by mirroring this structure in our code.

> I'm not certain what format/working groups such a discussion should involve

I'm not against filing a "type: discussion" issue in the `amphtml` repo, but I suspect the cost outweighs the benefit in this case.

**Comment by lannka** [comment]
I like the idea of grouping similar extensions together. But as @rsimha mentioned, it might need some work on our gulp & release process.

**Comment by rcebulko** [comment]
Since this targets a relatively small use-case (I see a total of 8 directories following this pattern in `amphtml/extensions`), I'm going to close this feature request for now. PRs adding these directories are currently rare enough that getting an approval from an owner of `extensions/` doesn't seem excessively onerous, and if that number grows the resolution discussed above of adding to `extensions/OWNERS` is available as an option. If more working groups request this for other use cases, it can be reconsidered.
