### ISSUE TITLE
[bundle-size] Blocking check for bundle size changes for files other than `v0.js`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amp-github-apps#617]
Continuing the work that started in #271. @ampproject/wg-infra discussed this plan offline and we decided on the following:

We'll add an `APPROVERS.json` file to bundle-size directory of http://github.com/ampproject/amphtml that specifies which team(s) members can approved which *compiled* files (e.g., `dist/v0.js`, `dist/v0/amp-story-1.0.js`) and what's the allowed growth threshold (`0.1` == 0.1kb) before requiring approval. Unspecified files will not require approvals at all.

```json5
{
  "dist/v0.js": {
    "approvers": ["ampproject/wg-performance", "ampproject/wg-runtime"],
    "threshold": 0.1
  },
  "dist/amp4ads-v0.js": {
    "approvers": ["ampproject/wg-ads"],
    "threshold": 0.1
  },
  "dist/v0/amp-story-0.1.js": {
    "approvers": ["ampproject/wg-stories"],
    "threshold": 0.5
  },
  "dist/v0/amp-story-1.0.js": {
    "approvers": ["ampproject/wg-stories"],
    "threshold": 0.5
  },
  // …
}
```

To simplify this model, only teams will be allowed in the `approvers` list, not individual. Also, PRs that modify files that require approval from more than one *set* of teams will fall back to require approval from @ampproject/wg-runtime or @ampproject/wg-performance. Members of @ampproject/wg-infra will still be able to approve any bundle-size change.

**Comment by rcebulko** [comment]
Could the `dist` prefix be excluded, if it only applies to files in `dist`?

**Comment by danielrozenberg** [comment]
Yeah but I already pass `dist/` explicitly everywhere in this app so might as well. Space is cheap 🙃
