### ISSUE TITLE
[bundle-size] Show size delta even after approval

### ISSUE THREAD

**Issue by choumx** [ampproject/amp-github-apps#686]
It'd be nice to be able to see the bundle size delta for a PR even after it's approved. E.g. this PR was approved by someone else before I had a chance to see the delta.

![image](https://user-images.githubusercontent.com/20525523/73968253-60fc1580-48e7-11ea-8db0-cfd7dbff3a6d.png)

> approved by @kevinkimball
The bundle size change(s) of this pull request were approved by @kevinkimball

https://github.com/ampproject/amphtml/pull/26609/checks?check_run_id=429052067

**Comment by danielrozenberg** [comment]
This seems like a reasonable request :)

**Comment by jridgewell** [comment]
Yes please

**Comment by danielrozenberg** [comment]
@jridgewell:
> Yes please

See #895 :)
