### ISSUE TITLE
[owners] Disable "notify owner" comments on draft PRs

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#708]
Follow up to #587, which has been fixed.

The auto-commenting feature of owners bot is very useful during the regular PR workflow, and has alerted me numerous times to changes I wouldn't have seen otherwise. However, it is quite noisy in the case of draft PRs.

Two recent examples are https://github.com/ampproject/amphtml/pull/26723#issuecomment-584413541 and https://github.com/ampproject/amphtml/pull/26779#issuecomment-585494168.

Can we disable auto-commenting for draft PRs?

More context: https://github.com/ampproject/amphtml/pull/26723#issuecomment-584423034

/cc @ampproject/wg-infra for additional comments.

**Comment by rcebulko** [comment]
Update has been deployed :+1:

**Comment by rsimha** [comment]
Reopening because the bot is still commenting on draft PRs.

https://github.com/ampproject/amphtml/pull/26878#issuecomment-589212107

**Comment by rcebulko** [comment]
Bug: It was only checking for drafts on newly opened PRs, not on `pull_request.synchronize` or the other PR events. Patching.
