### ISSUE TITLE
Wrap Owners Bot files in code blocks

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amp-github-apps#718]
Eg, https://github.com/ampproject/amphtml/pull/26901#issuecomment-589441937

We should make wrap the files list in a code block to differentiate it from normal text.

```
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/index.js
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/test/fixtures/transform/deep-array/input.js
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/test/fixtures/transform/deep-array/options.json
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/test/fixtures/transform/deep/input.js
```

vs
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/index.js
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/test/fixtures/transform/deep-array/input.js
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/test/fixtures/transform/deep-array/options.json
- build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/test/fixtures/transform/deep/input.js

**Comment by rcebulko** [comment]
Update deployed
