### ISSUE TITLE
[onduty] Add macros to assign release-on-duty and build-cop

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amp-github-apps#778]
Maybe `/assign-release` and `/assign-build`? (I have absolutely no strong opinion here, other than not liking the term "build-cop" itself, but not enough to call any vetoes)

**Comment by rcebulko** [comment]
I wasn't thinking of appending this to the invite bot, I was thinking of a separate uber-simple bot that listens for like `/release-cop` and `/build-cop` and comments @mentioning them. Past that point I'd leave it to the thread to determine if they should assign or not

**Comment by danielrozenberg** [comment]
That also works :) I figured it's within the scope of the invite bot because it already has a /tryassign action

**Comment by rcebulko** [comment]
My inclination would be for now to just spin up another small Cloud Function for this, and if we find a third case where we want to support macros, maybe it becomes worthwhile to merge it all somehow

**Comment by rcebulko** [comment]
The more I've thought about this, the more I'm leaning toward an approach of having two dedicated teams like `@ampproject/release-onduty` and `@ampproject/build-cop`, and let a cron job with access to the rotations system update those teams automatically. This would fit more easily into the workflow of most developers who are used to tagging people, and would allow for assigning issues and PRs to those aliases

**Comment by danielrozenberg** [comment]
Fine by me 🤷‍♂

**Comment by mrjoro** [comment]
SGTM; thanks!

**Comment by rcebulko** [comment]
This is done; closing.
