### ISSUE TITLE
Consolidate owners notifications for the same file / set of files

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-github-apps#799]
For example, [this](https://github.com/ampproject/amphtml/pull/27960#issuecomment-618072396) notification. What if it looked like this instead? Possible? Easy? 😃 

````
Hey @gmajoulet, @newmuis, and @enriqe, these files were changed:
```
extensions/amp-story/0.1/amp-story-info-dialog.js
extensions/amp-story/0.1/media-pool.js
extensions/amp-story/1.0/amp-story-info-dialog.js
extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/media-pool.js
```
````

**Comment by rcebulko** [comment]
Quite doable! I'll put it in the queue :)

**Comment by rsimha** [comment]
Yay! https://github.com/ampproject/amphtml/pull/28128#issuecomment-621618618

**Comment by rsimha** [comment]
Another example, where three owners subscribed to mostly similar (but not identical) sets of files: https://github.com/ampproject/amphtml/pull/28368#issuecomment-627639276 (see `amp-story` section)

Not sure if it's easy / desirable to de-dupe (or shorten?) in this case, but figured it's worth mentioning.

Related: #852

**Comment by rcebulko** [comment]
I think #852 would take higher precedence here. In general, I don't think we should try to be too clever about the grouping. We could try to group based on subsets of the file lists, but I think to a degree that becomes even less clear. Ex. If I'm watching directories A, B, and C, you're watching A and C, Esther's watching B, now I have to look across three different comments to find what's relevant to me, you have to look across two non-consecutive file lists, etc. I think we may be at the point of diminishing returns w.r.t. grouping within the actual comments, and the best we can do us cut them down in size for very large PRs where this is most likely to happen anyway--which, as you pointed out in #852, is a fairly rare occurrence.

I'm inclined to leave this as closed for the time being, but can re-open if it becomes a pain point even after trimming the comment size
