### ISSUE TITLE
Invite bot should handle expired/no-longer existing invitations

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amp-github-apps#876]
User was invited once here, ~1.5 months ago:

https://github.com/ampproject/amphtml/issues/27762

User did not accept invite, so I tried to invite again. Bot won't create a second invite:

https://github.com/ampproject/amphtml/issues/28708

When going to `https://github.com/orgs/ampproject/invitation`, invitation is no longer there:

![image](https://user-images.githubusercontent.com/254946/83905404-79096780-a716-11ea-95e4-dc625fc24d5a.png)

**Comment by rcebulko** [comment]
According to [this blog post](https://github.blog/changelog/2020-02-05-self-expiring-repository-and-organization-invitations/#:~:text=Invitations%20to%20join%20an%20organization,days%20after%20they%20are%20created.), invitations expire after 7 days. This can be handled by adding a `invited_at` column to the DB and filtering by that timestamp when checking if an invitation is pending.
