### ISSUE TITLE
[test-case-reporting] Collect data within Travis Job

### ISSUE THREAD

**Issue by Rafer45** [ampproject/amp-github-apps#885]
/cc @rcebulko
Part of #881

**Comment by Rafer45** [comment]
Closed by https://github.com/ampproject/amphtml/pull/28943.

**Comment by rcebulko** [comment]
Side-note: If you include `Closes #885` in the PR description, it would automatically close the associated issue

**Comment by Rafer45** [comment]
That was intentional, but I forgot to re-open the issue after reverting the push.

**Comment by Rafer45** [comment]
Working on a new approach to decouple reporting.
